server:
  port: 8083
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/darkprado-db
    username: darkprado
    password: pgpwd4dark
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
#  sql:
#    init:
#      mode: always
#      data-locations: data.sql
#      schema-locations: classpath:schema.sql
